export type Photo = {
  id: number;
  smallSrc: string;
  mediumSrc: string;
  title: string;
  location: string;
  state: string;
  camera: string;
  film: string;
  smallWidth: number;
  smallHeight: number;
  mediumWidth: number;
  mediumHeight: number;
};

export const images: Photo[] = [
  {
    id: 1,
    smallSrc: "/photos/01-small.jpg",
    mediumSrc: "/photos/01-medium.jpg",
    title: "Taylor Rose double exposed with a rose",
    location: "San Simeon",
    state: "California",
    camera: "Mamiya 645",
    film: "Kodak Gold 200",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 2,
    smallSrc: "/photos/02-small.jpg",
    mediumSrc: "/photos/02-medium.jpg",
    title: "Sun flare on the dunes",
    location: "White Sands National Park",
    state: "New Mexico",
    camera: "Mamiya 645",
    film: "Kodak Ektar 100",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 3,
    smallSrc: "/photos/03-small.jpg",
    mediumSrc: "/photos/03-medium.jpg",
    title: "Wildflowers by Jackson Lake",
    location: "Grand Teton National Park",
    state: "Wyoming",
    camera: "Canon AE-1",
    film: "Kodak Ektar 100",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 4,
    smallSrc: "/photos/04-small.jpg",
    mediumSrc: "/photos/04-medium.jpg",
    title: "Taylor on the dock at Sewell Park",
    location: "San Marcos",
    state: "Texas",
    camera: "Canon AE-1",
    film: "Kodak Portra 400",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 5,
    smallSrc: "/photos/05-small.jpg",
    mediumSrc: "/photos/05-medium.jpg",
    title: "Flock of birds above the coastline",
    location: "Big Sur",
    state: "California",
    camera: "Mamiya 645",
    film: "Kodak Tri-X 400",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 6,
    smallSrc: "/photos/06-small.jpg",
    mediumSrc: "/photos/06-medium.jpg",
    title: "Sunset double exposed",
    location: "Crater Lake National Park",
    state: "Oregon",
    camera: "Canon AE-1",
    film: "Kodak Portra 400",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 7,
    smallSrc: "/photos/07-small.jpg",
    mediumSrc: "/photos/07-medium.jpg",
    title: "Taylor double exposed with the sunset",
    location: "White Sands National Park",
    state: "New Mexico",
    camera: "Mamiya 645",
    film: "Kodak Ektar 100",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 8,
    smallSrc: "/photos/08-small.jpg",
    mediumSrc: "/photos/08-medium.jpg",
    title: "Santa Elena Canyon at sunrise",
    location: "Big Bend National Park",
    state: "Texas",
    camera: "Mamiya 645",
    film: "Kodak Portra 400",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 9,
    smallSrc: "/photos/09-small.jpg",
    mediumSrc: "/photos/09-medium.jpg",
    title: "Wildflowers above McWay Falls",
    location: "Big Sur",
    state: "California",
    camera: "Mamiya 645",
    film: "Kodak Portra 400",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 10,
    smallSrc: "/photos/10-small.jpg",
    mediumSrc: "/photos/10-medium.jpg",
    title: "Mirror portrait during sunset",
    location: "White Sands National Park",
    state: "New Mexico",
    camera: "Mamiya 645",
    film: "Kodak Gold 200",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 11,
    smallSrc: "/photos/11-small.jpg",
    mediumSrc: "/photos/11-medium.jpg",
    title: "Sunset over McWay Falls",
    location: "Big Sur",
    state: "California",
    camera: "Mamiya 645",
    film: "Kodak Gold 200",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 12,
    smallSrc: "/photos/12-small.jpg",
    mediumSrc: "/photos/12-medium.jpg",
    title: "Double exposure of sunrise at the Guadalupe River",
    location: "Canyon Lake",
    state: "Texas",
    camera: "Mamiya 645",
    film: "Kodak Portra 400",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 13,
    smallSrc: "/photos/13-small.jpg",
    mediumSrc: "/photos/13-medium.jpg",
    title: "Sunrise over Mount Rainier",
    location: "Sunrise",
    state: "Washington",
    camera: "Mamiya 645",
    film: "Kodak Portra 400",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 14,
    smallSrc: "/photos/14-small.jpg",
    mediumSrc: "/photos/14-medium.jpg",
    title: "Sahalie Falls flowing into the McKenzie River",
    location: "Willamette National Forest",
    state: "Oregon",
    camera: "Canon AE-1",
    film: "Kodak Portra 400",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
  {
    id: 15,
    smallSrc: "/photos/15-small.jpg",
    mediumSrc: "/photos/15-medium.jpg",
    title: "Foggy forest road",
    location: "Redwoods",
    state: "California",
    camera: "Mamiya 645",
    film: "Kodak Portra 400",
    smallWidth: 600,
    smallHeight: 800,
    mediumWidth: 975,
    mediumHeight: 1300,
  },
  {
    id: 16,
    smallSrc: "/photos/16-small.jpg",
    mediumSrc: "/photos/16-medium.jpg",
    title: "Wildflower meadow below Mount Rainier",
    location: "Paradise",
    state: "Washington",
    camera: "Canon AE-1",
    film: "Kodak Portra 400",
    smallWidth: 800,
    smallHeight: 600,
    mediumWidth: 1300,
    mediumHeight: 975,
  },
];
